# Generated by Django 5.2.8 on 2026-04-12 17:52

import apps.jobs.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_userprofile_email_userprofile_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cnpj",
                    models.CharField(
                        help_text="CNPJ da empresa (com ou sem máscara)",
                        max_length=18,
                        unique=True,
                        validators=[apps.jobs.validators.validate_cnpj],
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Razão social ou nome fantasia", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(help_text="E-mail de contato da empresa", max_length=254),
                ),
                (
                    "telefone",
                    models.CharField(help_text="Telefone de contato (com DDD)", max_length=20),
                ),
                (
                    "endereco",
                    models.TextField(blank=True, help_text="Endereço completo da empresa"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, help_text="Descrição sobre a empresa (opcional)"),
                ),
                (
                    "contato_nome",
                    models.CharField(help_text="Nome da pessoa responsável", max_length=255),
                ),
                (
                    "contato_cargo",
                    models.CharField(help_text="Cargo da pessoa responsável", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovada"),
                            ("blocked", "Bloqueada"),
                        ],
                        default="pending",
                        help_text="Status da empresa no sistema",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="jobs_compan_created_d66ba5_idx"),
                    models.Index(fields=["status"], name="jobs_compan_status_353d9c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(help_text="Título da vaga", max_length=255)),
                ("descricao", models.TextField(help_text="Descrição detalhada da vaga")),
                (
                    "requisitos",
                    models.TextField(
                        blank=True, help_text="Requisitos e qualificações necessárias"
                    ),
                ),
                (
                    "salario",
                    models.CharField(
                        blank=True, help_text="Faixa salarial ou 'A combinar'", max_length=100
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        help_text="Tipo da vaga (Estágio, CLT, PJ, etc.)", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("pending", "Pendente"),
                            ("approved", "Aprovada"),
                            ("expired", "Expirada"),
                        ],
                        default="draft",
                        help_text="Status da vaga no sistema",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa que oferece a vaga",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaga",
                "verbose_name_plural": "Vagas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Vaga para qual o aluno se candidatou",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Aluno que se candidatou",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidatura",
                "verbose_name_plural": "Candidaturas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobSearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_term",
                    models.CharField(help_text="Termo de busca utilizado", max_length=255),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Localização da busca", max_length=255, null=True
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de vaga (estágio, CLT, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "results_count",
                    models.IntegerField(default=0, help_text="Número de resultados encontrados"),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Filtros aplicados na busca"
                    ),
                ),
                (
                    "results_preview",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Preview dos primeiros resultados (máx 5)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuário que realizou a busca",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_searches",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Busca de Vagas",
                "verbose_name_plural": "Logs de Buscas de Vagas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["-created_at"], name="jobs_job_created_77460a_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["company", "status"], name="jobs_job_company_797da4_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="jobs_job_status_7d017a_idx"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["-created_at"], name="jobs_jobapp_created_9043f9_idx"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "-created_at"], name="jobs_jobapp_user_id_898a69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["job", "-created_at"], name="jobs_jobapp_job_id_3282e7_idx"),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("user", "job"), name="unique_application_per_user_job"
            ),
        ),
        migrations.AddIndex(
            model_name="jobsearchlog",
            index=models.Index(fields=["-created_at"], name="jobs_jobsea_created_6f5265_idx"),
        ),
        migrations.AddIndex(
            model_name="jobsearchlog",
            index=models.Index(
                fields=["user", "-created_at"], name="jobs_jobsea_user_id_d2ae3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobsearchlog",
            index=models.Index(fields=["search_term"], name="jobs_jobsea_search__1e205c_idx"),
        ),
    ]
