# Generated by Django 5.2.8 on 2026-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_company_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Motivo da rejeição (preenchido automaticamente ao rejeitar)",
                null=True,
            ),
        ),
    ]
