# Generated by Django 5.2.8 on 2026-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('expired', 'Expirada')], default='draft', help_text='Status da vaga no sistema', max_length=20),
        ),
    ]
