# Generated by Django 6.0 on 2026-04-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_add_rejected_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Rascunho'),
                    ('pending', 'Pendente'),
                    ('approved', 'Aprovada'),
                    ('rejected', 'Rejeitada'),
                    ('expired', 'Expirada'),
                    ('removed', 'Removida'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
    ]
