# Generated by Django 5.2.8 on 2026-05-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20260415_0858'),
        ('users', '0006_userprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('expired', 'Expirada'), ('removed', 'Removida')], default='draft', help_text='Status da vaga no sistema', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobsearchlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuário que realizou a busca (null para buscas admin/weekly review)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_searches', to='users.userprofile'),
        ),
    ]
