# Generated by Django 6.0 on 2026-05-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_searchterm_jobspy_fields'),
        ('jobs', '0006_job_search_log_nullable_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetched_date', models.DateField(db_index=True, help_text='Data em que a vaga foi capturada (para limpeza e filtro)')),
                ('title', models.CharField(help_text='Título da vaga', max_length=255)),
                ('company', models.CharField(help_text='Empresa', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('job_url', models.URLField(help_text='Link direto para a vaga', max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('job_type', models.CharField(blank=True, default='', max_length=50)),
                ('is_manual', models.BooleanField(default=False, help_text='Vaga adicionada manualmente pelo admin (BOT-04)')),
                ('search_term', models.ForeignKey(help_text='Termo de busca que gerou esta vaga', on_delete=django.db.models.deletion.CASCADE, related_name='daily_jobs', to='courses.searchterm')),
            ],
            options={
                'verbose_name': 'Vaga do Dia',
                'verbose_name_plural': 'Vagas do Dia',
                'ordering': ['-fetched_date', 'title'],
                'indexes': [models.Index(fields=['fetched_date', 'search_term'], name='jobs_dailyj_fetched_8dfa2a_idx'), models.Index(fields=['search_term', 'fetched_date'], name='jobs_dailyj_search__14408c_idx')],
                'unique_together': {('search_term', 'job_url', 'fetched_date')},
            },
        ),
    ]
