# Generated by Django 5.2.15 on 2026-06-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_seed_areas"),
        ("jobs", "0007_dailyjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Áreas para as quais a vaga é ofertada. Vazio = todas.",
                related_name="jobs",
                to="courses.area",
                verbose_name="Áreas",
            ),
        ),
    ]
