# Generated by Django 5.2.15 on 2026-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_job_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="message",
            field=models.TextField(blank=True, help_text="Recado opcional do aluno para a empresa"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="profile_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Cópia do mini-perfil do aluno no momento da candidatura (histórico imutável)",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("vista", "Vista"),
                    ("contatado", "Contatado"),
                    ("rejeitada", "Rejeitada"),
                ],
                default="pending",
                help_text="Status da candidatura no acompanhamento da empresa",
                max_length=20,
            ),
        ),
    ]
