# Generated by Django 6.0 on 2025-12-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Nome do curso", max_length=100)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código do curso (ex: COENS)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição detalhada do curso", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Curso ativo no sistema"),
                ),
                ("order", models.IntegerField(default=0, help_text="Ordem de exibição")),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="Nível do curso (ex: Graduação, Pós-graduação)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        help_text="Modalidade do curso (ex: Presencial, EAD)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duração do curso em semestres", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("term", models.CharField(help_text="Termo de busca para vagas", max_length=100)),
                ("is_default", models.BooleanField(default=True, help_text="Termo padrão/ativo")),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Prioridade na busca (maior = mais importante)"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termo de Busca",
                "verbose_name_plural": "Termos de Busca",
                "ordering": ["-priority", "term"],
                "unique_together": {("course", "term")},
            },
        ),
    ]
