# Generated by Django 6.0 on 2026-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='country_indeed',
            field=models.CharField(choices=[('Brazil', 'Brasil'), ('USA', 'Estados Unidos'), ('Argentina', 'Argentina'), ('Canada', 'Canadá'), ('Portugal', 'Portugal'), ('UK', 'Reino Unido'), ('Australia', 'Austrália'), ('Germany', 'Alemanha'), ('France', 'França'), ('Spain', 'Espanha'), ('Mexico', 'México'), ('Chile', 'Chile')], default='Brazil', help_text='País para busca no Indeed e Glassdoor', max_length=50),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='distance',
            field=models.IntegerField(blank=True, help_text='Distância em milhas do local de busca (padrão jobspy: 50)', null=True),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='hours_old',
            field=models.IntegerField(default=72, help_text='Considerar vagas publicadas nas últimas N horas'),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='Filtrar apenas vagas remotas'),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='job_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'Tempo Integral'), ('parttime', 'Meio Período'), ('internship', 'Estágio'), ('contract', 'Contrato'), ('temporary', 'Temporário'), ('other', 'Outro')], help_text='Tipo de vaga', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='linkedin_company_ids',
            field=models.CharField(blank=True, help_text='IDs de empresas no LinkedIn separados por vírgula (ex: 123456,789012)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='linkedin_fetch_description',
            field=models.BooleanField(default=False, help_text='Buscar descrição completa no LinkedIn (aumenta o tempo de busca)'),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='location',
            field=models.CharField(default='Curitiba, PR', help_text='Localização geográfica da busca', max_length=100),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='offset',
            field=models.IntegerField(default=0, help_text='Offset para paginação dos resultados de busca'),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='results_wanted',
            field=models.IntegerField(default=10, help_text='Número máximo de vagas por termo de busca'),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='site_name',
            field=models.CharField(default='linkedin,indeed,glassdoor', help_text='Sites de busca separados por vírgula: linkedin, indeed, glassdoor, zip_recruiter, google', max_length=100),
        ),
    ]
