# Generated by Django 5.2.15 on 2026-06-13 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_searchterm_jobspy_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da grande área (ex.: Tecnologia da Informação)",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome da área",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador curto opcional (ex.: ti, eng)",
                        max_length=30,
                        null=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição da área", verbose_name="Descrição"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji usado no menu do bot (opcional)",
                        max_length=10,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Área ativa no sistema", verbose_name="Ativa"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Ordem de exibição", verbose_name="Ordem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Grande área de conhecimento do curso",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.area",
                verbose_name="Área",
            ),
        ),
    ]
