# Generated by Django 6.0 on 2025-12-05 18:57

import django.db.models.deletion
import infra.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="ID do usuário no WhatsApp (ex: 554199999999@c.us)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "ra",
                    models.CharField(
                        blank=True, help_text="Registro Acadêmico", max_length=20, null=True
                    ),
                ),
                (
                    "utfpr_password",
                    infra.security.fields.EncryptedCharField(
                        blank=True,
                        help_text="Senha do Portal (criptografada)",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("is_authenticated_utfpr", models.BooleanField(default=False)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "current_action",
                    models.CharField(
                        blank=True,
                        help_text="Estado atual do fluxo conversacional do bot",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "flow_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados temporários do fluxo conversacional",
                    ),
                ),
                (
                    "selected_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_by_users",
                        to="courses.course",
                    ),
                ),
                (
                    "selected_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_by_users",
                        to="courses.searchterm",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
