# Generated by Django 5.2.8 on 2026-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail do aluno (@alunos.utfpr.edu.br)",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Senha hash (Django User integração futura)",
                max_length=128,
                null=True,
            ),
        ),
    ]
