# Generated by Django 5.2.8 on 2025-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_current_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="flow_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Dados temporários do fluxo conversacional"
            ),
        ),
    ]
