# Generated by Django 6.0 on 2026-05-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_searchterm_jobspy_fields'),
        ('users', '0005_remove_conversation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Curso preferido do aluno (salvo automaticamente na 1ª busca)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='courses.course'),
        ),
    ]
