# Generated by Django 6.0 on 2026-06-10 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_dailyjob'),
        ('users', '0006_userprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa vinculada a este número WhatsApp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_users', to='jobs.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_confirmation_sent_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora do envio do email de confirmação de empresa', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_confirmation_token',
            field=models.CharField(blank=True, help_text='Token para confirmar vínculo WhatsApp-empresa via email', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_company_authenticated',
            field=models.BooleanField(default=False, help_text='Indica se este número está autenticado como empresa'),
        ),
    ]
