# Generated by Django 5.2.15 on 2026-06-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_userprofile_company_auth"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "periodo",
                    models.CharField(
                        blank=True, help_text="Período/semestre atual do aluno", max_length=40
                    ),
                ),
                (
                    "skills",
                    models.TextField(blank=True, help_text="Principais habilidades/competências"),
                ),
                ("linkedin_url", models.URLField(blank=True, help_text="Perfil do LinkedIn")),
                ("cv_url", models.URLField(blank=True, help_text="Link para currículo/portfólio")),
                ("bio", models.TextField(blank=True, help_text="Breve apresentação")),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Aluno dono do mini-perfil",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mini-perfil do aluno",
                "verbose_name_plural": "Mini-perfis dos alunos",
            },
        ),
    ]
