# Generated by Django 6.0 on 2025-12-05 18:57

import django.db.models.deletion
import infra.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("waha_url", models.URLField(blank=True)),
                (
                    "waha_api_key",
                    infra.security.fields.EncryptedCharField(blank=True, max_length=512),
                ),
                ("waha_session", models.CharField(blank=True, max_length=100)),
                ("dashboard_username", models.CharField(blank=True, max_length=150)),
                (
                    "dashboard_password",
                    infra.security.fields.EncryptedCharField(blank=True, max_length=512),
                ),
                ("admin_username", models.CharField(blank=True, max_length=150)),
                (
                    "admin_password",
                    infra.security.fields.EncryptedCharField(blank=True, max_length=512),
                ),
            ],
            options={
                "verbose_name": "Configuração do Bot",
                "verbose_name_plural": "Configurações do Bot",
            },
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("welcome", "Boas-vindas / Menu"),
                            ("login_prompt", "Solicitar Login"),
                            ("login_success", "Login com Sucesso"),
                            ("login_error", "Erro no Login"),
                            ("logout_success", "Logout com Sucesso"),
                            ("course_selection", "Seleção de Curso"),
                            ("term_selection", "Seleção de Termo"),
                            ("no_results", "Sem Resultados"),
                            ("unknown_command", "Comando Desconhecido"),
                            ("error_generic", "Erro Genérico"),
                        ],
                        help_text="Chave identificadora da mensagem",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Conteúdo da mensagem. Use {variaveis} para interpolação se necessário."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Descrição do uso desta mensagem", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem do Bot",
                "verbose_name_plural": "Mensagens do Bot",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="BotHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline"), ("error", "Erro")],
                        help_text="Status do bot",
                        max_length=20,
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(blank=True, help_text="Tempo de resposta em ms", null=True),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensagem de erro (se houver)", null=True
                    ),
                ),
                (
                    "session_status",
                    models.CharField(
                        default="unknown", help_text="Status da sessão WAHA", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Verificação de Saúde do Bot",
                "verbose_name_plural": "Verificações de Saúde do Bot",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="bot_botheal_created_8ecffa_idx"),
                    models.Index(fields=["status"], name="bot_botheal_status_49b4ed_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BotMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_name", models.CharField(help_text="Nome da métrica", max_length=100)),
                ("value", models.FloatField(help_text="Valor da métrica")),
                (
                    "metadata",
                    models.JSONField(blank=True, help_text="Metadados adicionais", null=True),
                ),
            ],
            options={
                "verbose_name": "Métrica do Bot",
                "verbose_name_plural": "Métricas do Bot",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "-created_at"], name="bot_botmetr_metric__60be81_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_content", models.TextField(help_text="Conteúdo da mensagem")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("SENT", "Enviada pelo Bot"), ("RECEIVED", "Recebida do Usuário")],
                        max_length=10,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        default="default", help_text="ID da sessão WAHA", max_length=100
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Metadados adicionais da mensagem", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Interação",
                "verbose_name_plural": "Logs de Interações",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="bot_interac_created_78511f_idx"),
                    models.Index(
                        fields=["user", "-created_at"], name="bot_interac_user_id_765f49_idx"
                    ),
                    models.Index(fields=["message_type"], name="bot_interac_message_7e20f2_idx"),
                ],
            },
        ),
    ]
