# Generated by Django 5.2.8 on 2026-04-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmessage",
            name="key",
            field=models.CharField(
                choices=[
                    ("welcome", "Boas-vindas / Menu"),
                    ("login_prompt", "Solicitar Login"),
                    ("login_prompt_ra", "Solicitar RA"),
                    ("login_prompt_password", "Solicitar Senha"),
                    ("login_prompt_email", "Solicitar Email"),
                    ("login_success", "Login com Sucesso"),
                    ("login_error", "Erro no Login"),
                    ("logout_success", "Logout com Sucesso"),
                    ("course_selection", "Seleção de Curso"),
                    ("term_selection", "Seleção de Termo"),
                    ("no_results", "Sem Resultados"),
                    ("unknown_command", "Comando Desconhecido"),
                    ("error_generic", "Erro Genérico"),
                ],
                help_text="Chave identificadora da mensagem",
                max_length=50,
                unique=True,
            ),
        ),
    ]
