# Generated by Django 5.2.8 on 2026-04-18 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_add_login_prompt_email_key"),
        ("courses", "0001_initial"),
        ("users", "0004_add_email_verification_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_action",
                    models.CharField(
                        blank=True,
                        help_text="Estado atual do fluxo conversacional do bot",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "flow_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados temporários do fluxo conversacional",
                    ),
                ),
                (
                    "selected_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_selections",
                        to="courses.course",
                    ),
                ),
                (
                    "selected_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_selections",
                        to="courses.searchterm",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Perfil do usuário associado ao estado conversacional",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_state",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Conversa",
                "verbose_name_plural": "Estados de Conversa",
            },
        ),
    ]
