# Generated by Django 5.2.8 on 2025-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_botconfiguration_admin_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botconfiguration",
            name="admin_password",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="botconfiguration",
            name="admin_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="botconfiguration",
            name="dashboard_password",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="botconfiguration",
            name="dashboard_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="botconfiguration",
            name="waha_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="botconfiguration",
            name="waha_session",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="botconfiguration",
            name="waha_url",
            field=models.URLField(blank=True),
        ),
    ]
