# Generated by Django 5.2.8 on 2025-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_alter_botconfiguration_admin_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("welcome", "Boas-vindas / Menu"),
                            ("login_prompt", "Solicitar Login"),
                            ("login_success", "Login com Sucesso"),
                            ("login_error", "Erro no Login"),
                            ("logout_success", "Logout com Sucesso"),
                            ("course_selection", "Seleção de Curso"),
                            ("term_selection", "Seleção de Termo"),
                            ("no_results", "Sem Resultados"),
                            ("unknown_command", "Comando Desconhecido"),
                            ("error_generic", "Erro Genérico"),
                        ],
                        help_text="Chave identificadora da mensagem",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Conteúdo da mensagem. Use {variaveis} para interpolação se necessário."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Descrição do uso desta mensagem", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem do Bot",
                "verbose_name_plural": "Mensagens do Bot",
                "ordering": ["key"],
            },
        ),
    ]
